version: '3'
services:
  coughsense:
    image: coughsense
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INPUT_MODE=s3
      - INPUT_DIR=/data/input
      - OUTPUT_DIR=/data/output
      - MODEL_FILENAME=model.pt
      - AUDIO_FILENAME=PID_82A_54_codec.wav
      - S3_KEY=audio_files/
      - S3_BUCKET=bhattis-coughsense
    volumes:
      - ./data/input:/data/input:ro
      - ./data/output:/data/output
